### ISSUE TITLE
提几点建议

### ISSUE THREAD

**Issue by alexzhu0592** [2227324689/gpmall#147]
1、es的数据同步通过全库查询更新的，这种效率很低的，可以通过 mysqlbinlog + canal + rocketmq，保证es数据的有序有效，可以参考gitee上的一个现成方案itopener-canal-es；
2、商品到购物车，如果没有付款，用延时队列实现半个小时订单被取消；
3、缓存项目是通过cachemanger这个入口进行管理的吗，建议直接用spring的@Cache做；

**Comment by alexzhu0592** [comment]
还有一点就是既然是maven项目，为什么parent是单独一个module

**Comment by 2227324689** [comment]
1. 看我的架构图
2. 已经在做了
3. 怎么用都可以，无所谓
4. 统一父控，这不是一个单机项目
